global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'golang'
    static_configs:
      - targets: ['docker.for.mac.localhost:8080']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['docker.for.mac.localhost:9100']
